// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovnwbrjbjcwylqdkkjsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bndicmpiamN3eWxxZGtranNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzE1MzcsImV4cCI6MjA1NjUwNzUzN30.kFz6ofhccLYEUq7MBCxA2FdNFF1wXGFK6dHD1w9xO40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);